"""empty message

Revision ID: 236405361dc2
Revises: f64e46e39c16
Create Date: 2024-08-07 16:20:33.701098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236405361dc2'
down_revision: Union[str, None] = 'f64e46e39c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    op.drop_column('images', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('disciplines', 'description')
    # ### end Alembic commands ###
