"""empty message

Revision ID: 7181edeb93c3
Revises: 236405361dc2
Create Date: 2024-08-09 13:22:15.509651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7181edeb93c3'
down_revision: Union[str, None] = '236405361dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
